# node from which initial footprint is read
footprint_source: /move_base/local_costmap/obstacle_layer_footprint/footprint_stamped

# 
robot_base_frame: /base_link
# frames to check for footprint adjustment
frames_to_check: /pg70_finger_left_link /arm_6_link /arm_4_link /tray_right_link /tray_left_link 
epsilon: 0.01
