name: gripper_controller

defaults:
  eds_pkg: cob_hardware_config
  eds_file: "cob3-8/config/Schunk_0_63.dcf"
  pos_to_device: "pos*2000000.0"
  pos_from_device: "obj6064/2000000.0"
  vel_to_device: "vel*2000000.0"
  vel_from_device: "obj606C*2000000.0"
modules:
  - name: pg70_finger_left_joint
    id: 12
