## joint_names
joint_names: [arm_1_joint, arm_2_joint, arm_3_joint, arm_4_joint, arm_5_joint, arm_6_joint, arm_7_joint]

## control_mode_adapter
max_command_silence: 0.5

## joint_state_controller
joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

## joint trajectory controller
joint_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints:
     - arm_1_joint
     - arm_2_joint
     - arm_3_joint
     - arm_4_joint
     - arm_5_joint
     - arm_6_joint
     - arm_7_joint
  constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      arm_1_joint: {trajectory: 0.1, goal: 0.1}
      arm_2_joint: {trajectory: 0.1, goal: 0.1}
      arm_3_joint: {trajectory: 0.1, goal: 0.1}
      arm_4_joint: {trajectory: 0.1, goal: 0.1}
      arm_5_joint: {trajectory: 0.1, goal: 0.1}
      arm_6_joint: {trajectory: 0.1, goal: 0.1}
      arm_7_joint: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10
  required_drive_mode: 7
  
## no further controllers available

# trajectory controller parameters
ptp_vel: 0.4 # rad/sec
ptp_acc: 0.2 # rad/sec^2
max_error: 0.15 # rad
