## Cartesian controller parameters
chain_base_link: arm_right_base_link
chain_tip_link: arm_right_7_link
root_frame: odom_combined

# twist controller parameters
twist_controller:
  base_compensation: false
  base_active: false
  base_ratio: 0.1
  max_vel_lin: 0.5
  max_vel_rot: 0.5
  max_vel_lin_base: 0.5
  max_vel_rot_base: 0.5

  # damping parameters
  numerical_filtering: false
  damping_method: 2  #MANIPULABILITY
  damping_factor: 0.2
  lambda_max: 0.1
  w_threshold: 0.005
  beta: 0.005
  eps_damping: 0.003
  # constraints and truncation
  constraint: 2 #WLN_JLA
  eps_truncation: 0.03
  k_H: -10.0  #Self-motion factor for GPM
  # limit enforcing
  keep_direction: true
  enforce_vel_limits: true
  enforce_pos_limits: true
  tolerance: 5.0
  
  # collision avoidance frames for obstacle distance
  collision_check_frames: [arm_right_5_link]

# frame_tracker + interactive_marker
frame_tracker:
  update_rate: 50.0
  tracking_frame: arm_right_7_target
  movable_trans: true
  movable_rot: true
  pid_trans_x: {p: 4.0, i: 0.0, d: 0.0, i_clamp: 0.0}
  pid_trans_y: {p: 4.0, i: 0.0, d: 0.0, i_clamp: 0.0}
  pid_trans_z: {p: 4.0, i: 0.0, d: 0.0, i_clamp: 0.0}
  pid_rot_x: {p: 4.0, i: 0.0, d: 0.0, i_clamp: 0.0}
  pid_rot_y: {p: 4.0, i: 0.0, d: 0.0, i_clamp: 0.0}
  pid_rot_z: {p: 4.0, i: 0.0, d: 0.0, i_clamp: 0.0}
  # abortion criteria - cfg
  cart_min_dist_threshold_lin: 0.01
  cart_min_dist_threshold_rot: 0.01
  twist_dead_threshold_lin: 0.05
  twist_dead_threshold_rot: 0.05
  twist_deviation_threshold_lin: 0.5
  twist_deviation_threshold_rot: 0.5
